### ISSUE TITLE
proteomicslfq process fails when running with decoys

### ISSUE THREAD

**Issue by veitveit** [nf-core/proteomicslfq#151]
I am running the UPS data set with the --add_decoy option:
```
nextflow run nf-core/proteomicslfq -r 1.0.0 -profile docker --input https://raw.githubusercontent.com/bigbio/proteomics-metadata-standard/master/annotated-projects/PXD001819/PXD001819.sdrf.tsv --database https://raw.githubusercontent.com/nf-core/test-datasets/proteomicslfq/testdata-aws/uniprot\_yeast\_reviewed\_isoforms\_ups1\_crap.fasta\_td.fasta -with-report -with-trace -with-timeline -resume --add_decoys true
```

The log file tells that there are "no proteins left after FDR filtering" and I get a lot of warnings of the kind 
```WARNING in SignalToNoiseEstimatorMedian: 2.7248% of all Signal-to-Noise estimates are too high, because the median was found in the rightmost histogram-bin. You should consider increasing 'max_intensity' (and maybe 'bin_count' with it, to keep bin width reasonable)
```

Am I missing any particular parameter setting?

Thanks!

**Comment by jpfeuffer** [comment]
I think the problem is, that the specific database in question already contains decoys. Instead, you would need to specify the decoy_affix.
This messes up FDR calculation quite a lot.

If you want to keep+quantify+export decoys, this is not possible in 1.0.0 and was only added to dev to support Triqler output which expects decoys. This might need refinement if we make it the default for e.g. also pmultiqc. The param for this is quantify_decoys.

**Comment by veitveit** [comment]
OK, thanks! Alternatively, I could also use a database without decoys, right?

And I should update you on the ELIXIR project at some point. Did you get my email?

**Comment by veitveit** [comment]
Works now
